export interface Country { code: string; name: string; dial: string; provinceLabel?: string; postalLabel?: string }
export const COUNTRIES: Country[] = [
  { code: "US", name: "United States", dial: "+1", provinceLabel: "State", postalLabel: "ZIP code" }, { code: "CA", name: "Canada", dial: "+1", provinceLabel: "Province", postalLabel: "Postal code" }, { code: "MX", name: "Mexico", dial: "+52", provinceLabel: "State" },
  { code: "GB", name: "United Kingdom", dial: "+44", provinceLabel: "County", postalLabel: "Postcode" }, { code: "IE", name: "Ireland", dial: "+353", provinceLabel: "County", postalLabel: "Eircode" }, { code: "DE", name: "Germany", dial: "+49" }, { code: "FR", name: "France", dial: "+33" }, { code: "ES", name: "Spain", dial: "+34", provinceLabel: "Province" }, { code: "IT", name: "Italy", dial: "+39", provinceLabel: "Province" }, { code: "NL", name: "Netherlands", dial: "+31" }, { code: "BE", name: "Belgium", dial: "+32" }, { code: "AT", name: "Austria", dial: "+43" }, { code: "CH", name: "Switzerland", dial: "+41", provinceLabel: "Canton" }, { code: "PT", name: "Portugal", dial: "+351" },
  { code: "SE", name: "Sweden", dial: "+46" }, { code: "DK", name: "Denmark", dial: "+45" }, { code: "NO", name: "Norway", dial: "+47" }, { code: "FI", name: "Finland", dial: "+358" }, { code: "PL", name: "Poland", dial: "+48" }, { code: "CZ", name: "Czechia", dial: "+420" }, { code: "TR", name: "Türkiye", dial: "+90" }, { code: "GR", name: "Greece", dial: "+30" },
  { code: "AU", name: "Australia", dial: "+61", provinceLabel: "State" }, { code: "NZ", name: "New Zealand", dial: "+64", provinceLabel: "Region" }, { code: "JP", name: "Japan", dial: "+81", provinceLabel: "Prefecture" }, { code: "KR", name: "South Korea", dial: "+82" }, { code: "SG", name: "Singapore", dial: "+65" }, { code: "HK", name: "Hong Kong", dial: "+852" }, { code: "IN", name: "India", dial: "+91", provinceLabel: "State", postalLabel: "PIN code" }, { code: "VN", name: "Vietnam", dial: "+84" }, { code: "TH", name: "Thailand", dial: "+66" }, { code: "ID", name: "Indonesia", dial: "+62" }, { code: "PH", name: "Philippines", dial: "+63" }, { code: "MY", name: "Malaysia", dial: "+60" },
  { code: "BR", name: "Brazil", dial: "+55", provinceLabel: "State" }, { code: "AR", name: "Argentina", dial: "+54", provinceLabel: "Province" }, { code: "CL", name: "Chile", dial: "+56" }, { code: "CO", name: "Colombia", dial: "+57" }, { code: "PE", name: "Peru", dial: "+51" },
  { code: "NG", name: "Nigeria", dial: "+234", provinceLabel: "State" }, { code: "GH", name: "Ghana", dial: "+233" }, { code: "KE", name: "Kenya", dial: "+254" }, { code: "ZA", name: "South Africa", dial: "+27", provinceLabel: "Province" }, { code: "EG", name: "Egypt", dial: "+20" }, { code: "MA", name: "Morocco", dial: "+212" }, { code: "AE", name: "United Arab Emirates", dial: "+971", provinceLabel: "Emirate" }, { code: "SA", name: "Saudi Arabia", dial: "+966" }, { code: "IL", name: "Israel", dial: "+972" },
];
export const countryByCode = (code?: string | null) => COUNTRIES.find((c) => c.code === (code ?? "").toUpperCase());
export const dialCodeFor = (code?: string | null) => countryByCode(code)?.dial ?? "+1";
